### ISSUE TITLE
Some problem

### ISSUE THREAD

**Issue by zhouhuirun2015** [Phylliida/UnityWindowsCapture#1]
This project functions very well, besides

When capture window, the cursor pos is wrong, 
When capture monitor(only one monitor in my PC), the picture looks like below:
![tim 20170930145316](https://user-images.githubusercontent.com/15274287/31043502-7b4bdc92-a5ef-11e7-8900-2ebcfd271a09.png)

**Comment by Phylliida** [comment]
What's happening there is that the texture isn't being updated so the mouse cursor is the only thing that is being drawn (so it is never erased when the screen updates)

Are you sure you are following the example? Make sure you call things in the same place it does.

**Comment by abrarrobotics** [comment]
Excellent Bro , Really Predicate your work.
I use your plugin, Its working fine , it capture desktop , and show web app , 
touch doesn't work and , it once open other application ,"that was Excellence",
and Chrome Runtime  kindly Help it out , Best Way is to export package Its Fix bugs.

Thanks For Your Cooperation.

"You make My Dream true".
![des](https://user-images.githubusercontent.com/25553583/40143425-d724524a-5974-11e8-98a3-f0ee6a4a8e2b.PNG)
